# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Modelspi3.py
# Created on: 2021-06-21 21:19:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Sheet1_ = "D:\\Latihan\\input\\Analisis_SPI_3Bln.xls\\Sheet1$"
anspi3_Layer = "anspi3_Layer"
Extent = "134.736755368791 -9.12036268946667 141.019399989921 -3.72268885227161"
PapuaSelatan = "PapuaSelatan"
idw_spi = "D:\\Latihan\\process\\idw_spi"
reclass_spi = "D:\\Latihan\\process\\reclass_spi"
polygon_spi_shp = "D:\\Latihan\\process\\polygon_spi.shp"
clip_spi_shp = "D:\\Latihan\\process\\clip_spi.shp"
intersect_spi_shp = "D:\\Latihan\\process\\intersect_spi.shp"
tabel_spi3_xls = "D:\\Latihan\\output\\tabel_spi3.xls"

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Sheet1_, "lon", "lat", anspi3_Layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "ANSPI3")

# Process: IDW
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = Extent
tempEnvironment1 = arcpy.env.mask
arcpy.env.mask = PapuaSelatan
arcpy.gp.Idw_sa(anspi3_Layer, "ANSPI3", idw_spi, "0.001", "2", "VARIABLE 12", "")
arcpy.env.extent = tempEnvironment0
arcpy.env.mask = tempEnvironment1

# Process: Reclassify
arcpy.gp.Reclassify_sa(idw_spi, "VALUE", "-10 -2 1;-2 -1.500000 2;-1.500000 -0.990000 3;-0.990000 0.990000 4;0.990000 1.500000 5;1.500000 2 6;2 10 7", reclass_spi, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(reclass_spi, polygon_spi_shp, "SIMPLIFY", "VALUE")

# Process: Clip
arcpy.Clip_analysis(polygon_spi_shp, PapuaSelatan, clip_spi_shp, "")

# Process: Intersect
arcpy.Intersect_analysis("D:\\Latihan\\process\\clip_spi.shp #;PapuaSelatan #", intersect_spi_shp, "ALL", "", "INPUT")

# Process: Table To Excel
arcpy.TableToExcel_conversion(intersect_spi_shp, tabel_spi3_xls, "ALIAS", "CODE")

