# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# spi.py
# suci pratiwi
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import os
#import shutil
import arcpy

#Working Directory : ---
dir = os.getcwd()
temp = dir+"\\process\\"
indir = dir+"\\input\\"
dirout = dir+"\\output\\"
mapdir = dir+"\\mxd\\"

#Buat Temporary Folder ------------------------------------------------------------
try:
	os.makedirs(temp)
except OSError:
	pass
#----------------------UBAH BAGIAN INI------------------------

bulan = "MARET-MEI 2021"
update = "Juni 2021"

arcpy.env.overwriteOutput =  True

# Local variables:
print "MULAI"

Sheet1_ = indir+"\\DATA_SPI.xls\\Sheet1$"
spi_layer = temp+"anspi3_Layer"
idw = temp+"idw_spi"
reclass = temp+"reclass_spi"
polygon = temp+"polygon_spi.shp"
clip = temp+"clip_spi.shp"
intersect = temp+"intersect_spi.shp"
tabel = dirout + "tabel_spi3.xls"
PapuaSelatan_shp = dir+"\\basemap\\PapuaSelatan.shp"
print ""


# Process: Make XY Event Layer
print "Make XY Event Layer"
arcpy.MakeXYEventLayer_management(Sheet1_, "LON", "LAT", spi_layer, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision", "")
print "selesai"
print ""

# Process: IDW
print "IDW"
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = PapuaSelatan_shp
tempEnvironment1 = arcpy.env.mask
arcpy.env.mask = PapuaSelatan_shp
arcpy.gp.Idw_sa(spi_layer, "ANSPI3", idw, "0.001", "2", "VARIABLE 12", "")
arcpy.env.extent = tempEnvironment0
arcpy.env.mask = tempEnvironment1
print "selesai"
print ""

# Process: Reclassify
print "Reclassify"
arcpy.gp.Reclassify_sa(idw, "VALUE", "-10 -2 1;-2 -1.500000 2;-1.500000 -0.990000 3;-0.990000 0.990000 4;0.990000 1.500000 5;1.500000 2 6;2 10 7", reclass, "DATA")
print "selesai"
print ""

# Process: Raster to Polygon
print "Raster to Polygon"
arcpy.RasterToPolygon_conversion(reclass, polygon, "SIMPLIFY", "VALUE")
print "selesai"
print ""

# Process: Clip
print "Clip "
arcpy.Clip_analysis(polygon, PapuaSelatan_shp, clip, "")
print "selesai"
print ""

# Process: Intersect
print "Intersect "
isect = clip + " #;'" + PapuaSelatan_shp + "' #"
arcpy.Intersect_analysis(isect, intersect, "ALL", "", "INPUT")
print "selesai"
print ""


# Process: CETAK JPG
print "Cetak Peta"
mxd = arcpy.mapping.MapDocument (dir+"\\mxd\\tes1.mxd")
mxd.title = (bulan)
mxd.author = (update)
arcpy.mapping.ExportToJPEG (mxd,dir+"\\output\\SPI3BLN_Update_"+update+".jpg")
print "selesai"
print ""

print "cetak tabel"
# Process: Table To Excel
arcpy.TableToExcel_conversion(intersect, tabel, "ALIAS", "CODE")

print "selesai"
print ""


