# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TES2.py
# Created on: 2021-06-20 10:33:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")
a=0
while a < 10:

# Local variables:
    NC = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\dataexcel\\GSMaP_202106100"+str(a)+"00.nc"
    print("GSMaP_202106100"+str(a)+"00.nc")
    SHP = "A:\\YUDI\\Prima\\DIKLATIKLIM\\jumat\\KALTIMFIXt.shp"
    tesshp = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\tesshp"
    rainrate_Layer = "rainrate"
    Extract = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb\\Extract"+"GSMaP_202106100"+str(a)
    Raster = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb\\Raster"+"GSMaP_202106100"+str(a)

# Process: Make NetCDF Raster Layer
    arcpy.MakeNetCDFRasterLayer_md(NC, "rainrate", "longitude", "latitude", rainrate_Layer, "", "", "BY_VALUE")

# Process: Extract by Mask
    arcpy.gp.ExtractByMask_sa(rainrate_Layer, SHP, Extract)

# Process: Raster to Point
    arcpy.RasterToPoint_conversion(Extract, Raster, "Value")

# Process: Feature Class To Shapefile (multiple)
    arcpy.FeatureClassToShapefile_conversion(Raster, tesshp)
    a=a+1

