# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tes3.py
# Created on: 2021-06-20 11:51:18.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import
import arcpy
import datetime
import time

named_tuple = time.localtime() # get struct_time
time_string = time.strftime("%j%H%M%S", named_tuple)

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")
arcpy.env.workspace = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb"

a=0
while a <10:

# Local variables:
    NC = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\dataexcel\\GSMaP_202106100"+str(a)+"00.nc"
    SHP = "A:\\YUDI\\Prima\\DIKLATIKLIM\\jumat\\KALTIMFIXt.shp"
    tesshp = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\tesshp"
    rainrate_Layer = "rainrate"
    Extract = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb\\Extract"+time_string
    Raster = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb\\Raster"+time_string
    Excel_Table = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\scratch\\Excel_Table06100"+str(a)+"00.xls"
    Idw_Raster = "A:\\YUDI\\Prima\\DIKLATIKLIM\\PYTHONSCRIPT\\New File Geodatabase.gdb\\Idw_Raster"

# Process: Make NetCDF Raster Layer
    arcpy.MakeNetCDFRasterLayer_md(NC, "rainrate", "longitude", "latitude", rainrate_Layer, "", "", "BY_VALUE")

# Process: Extract by Mask
    arcpy.gp.ExtractByMask_sa(rainrate_Layer, SHP, Extract)

# Process: Raster to Point
    arcpy.RasterToPoint_conversion(Extract, Raster, "Value")

# Process: Feature Class To Shapefile (multiple)
    arcpy.FeatureClassToShapefile_conversion(Raster, tesshp)

# Process: Table To Excel
    arcpy.TableToExcel_conversion(Raster, Excel_Table, "NAME", "CODE")

# Process: IDW
    arcpy.gp.Idw_sa(Raster, "grid_code", Idw_Raster, "0.02007493308", "2", "VARIABLE 12", "")

# Monitoring
    print(time.ctime()+" Export Excel_Table06100"+str(a)+"00.xls")
    a=a+1
